{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-sync.fullname" . }}
  labels:
    {{- include "vault-sync.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $entry := .Values.secrets }}
  {{ $key }}: {{ $entry | quote }}
  {{- end }}
{{- end }}